site_name: Infra-Shared

theme:
  name: material

plugins:
  - search
  - include-markdown

markdown_extensions:
  - smarty
  - toc:
      permalink: "#"
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: README.md
  - CoreOS:
      - os.md
      - butane.md
      - update.md
      - networking.md
      - credentials.md
      - healthchecks.md
  - pulumi.md
  - Examples:
      - examples/safe/README.md
  - scripts.md
  - development.md
