site_name: Infra-Shared

theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - docs/extra.css

plugins:
  - search
  - gen-files:
      scripts:
        - mkdocs_gensrc.py
  - include-markdown

markdown_extensions:
  - smarty
  - toc:
      permalink: "#"
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true # Allows linking to specific lines
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: README.md
  - CoreOS:
      - os.md
      - butane.md
      - update.md
      - networking.md
      - credentials.md
      - healthchecks.md
  - pulumi.md
  - Examples:
      - Fedora-CoreOS on Raspberry Pi: examples/safe/README.md
      - Postgresql Example Module: examples/modules/postgresql/README.md
      - Create a MitM CA Chain: examples/fake_ca/__init__.py.md
      - Templates for new projects:
          - scripts/create_skeleton.sh.md
          - examples/skeleton/Makefile.md
          - examples/skeleton/pyproject.toml.md
  - scripts.md
  - development.md
